# -*- coding: utf-8 -*-
"""Exercicios_aula8_python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XIFbzEzlcixbmhPJ4o5Bu7Jogu07o-Ap
"""

#Exercicios - Aula 8


frutas = ('maça', 'banana', 'morango', 'abacaxi', 'uva')
terceiro = frutas[2]
print(terceiro)

numeros = ( 1,5,11,66,99)
n = list(numeros)
print (n)

meses = ('Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro')
for m in meses:
  print(m)

notas = [5,6,7,8,9,10]
t = tuple(notas)
print(t)

ponto = (10,20)
x,y = ponto
print(f'''eixo x = {x}
eixo y = {y} ''')